# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.define "web_server" do |web|
      web.vm.box = "ubuntu/jammy64"
      web.vm.hostname = "web-cyal"
      
     
      web.vm.provider "virtualbox" do |vb|
          vb.name = "Web server"
          vb.memory = 3072
          vb.cpus = 2
      end
      
     
      web.vm.network "private_network", ip: "172.16.0.10"
      web.vm.network "public_network", ip: "10.99.0.10"
      
     
      web.vm.provision "shell", inline: <<-SHELL
          sudo apt update
          sudo apt install -y apache2
          sudo systemctl enable apache2
          sudo systemctl start apache2
          
         
          sudo mkdir -p /var/www/html/misitio
          echo '<!DOCTYPE html><html><head><title>Inicio</title></head><body><h1>Página de inicio</h1></body></html>' | sudo tee /var/www/html/misitio/index.html
          echo '<!DOCTYPE html><html><head><title>Nosotros</title></head><body><h1>Página sobre nosotros</h1></body></html>' | sudo tee /var/www/html/misitio/nosotros.html
          echo '<!DOCTYPE html><html><head><title>Contacto</title></head><body><h1>Página de contacto</h1></body></html>' | sudo tee /var/www/html/misitio/contacto.html
          
      
          sudo cp /var/www/html/index.html /var/www/html/misitio/imagen.jpg           
         
          sudo tee /etc/apache2/sites-available/misitio.conf <<EOF
          <VirtualHost *:80>
              DocumentRoot "/var/www/html/misitio"
              <Directory "/var/www/html/misitio">
                  Options Indexes FollowSymLinks
                  AllowOverride None
                  Require all granted
              </Directory>
          </VirtualHost>
          EOF
          
          sudo a2ensite misitio.conf
          sudo systemctl restart apache2
      SHELL
  end
end
