# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.hostname = "web-cyal"
  config.vm.provision "shell", inline: "apt update && apt install apache2 -y"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "web server"
    vb.memory = 3072
    vb.cpus = 2
  end
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "172.16.1.10"
  config.vm.network "public_network", ip: "10.99.1.10"
end
