# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "peru/my_ubuntu-20.04-server-amd64"
  config.vm.hostname = "servercyal"
  config.vm.synced_folder "./carpetadata", "/data", create=true
  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu server"
    vb.memory = 2048
    vb.cpus = 2
  end
end
