#!/bin/bash
#Para pedir una ip al usuario
echo -e "\e[34mEscribe una dirección IP en formato CIDR (p.e. 192.168.1.0/24). La máscara debe ser /8, /16 o /24.\e[0m"
read direccionip
#Separar la ip de la máscara
red=$( echo $direccionip | cut -d '/' -f 1)
mascara=$(echo $direccionip | cut -d '/' -f 2)
#Saber si la máscara es /8, /16 o /24
while [[ $mascara != '8' && $mascara != '16' && $mascara != '24' ]]
do
        echo -e "\e[31mLa máscara que has introducido no es /8, /16 ni /24. Ingresa una máscara válida.\e[0m"
        echo -e "\e[34mEscribe una dirección IP en formato CIDR (p.e. 192.168.1.0/24).\e[0m"
        read direccionip
        red=$(echo $direccionip | cut -d '/' -f 1)
        mascara=$(echo $direccionip | cut -d '/' -f 2)
done
#Con esto vamos a separar cada octeto de la IP
IFS='.' read -r -a octeto <<< $red
#Ahora vamos a hacer ping a cada una de las direcciones ip, para saber si hay equipos con esa ip
#y esas IPs las vamos a guardar en un archivo para luego detectar los puertos abiertos
ipsa="ips_activas.txt"
#y los puertos abiertos los guardaremos en un archivo
puertos_abiertos="puertos_abiertos.txt"
#vamos a limpiar estos archivos cada vez que empiece el script
> $ipsa
> $puertos_abiertos
if [ $mascara = '24' ]
then
        for i in {1..254}
        do
        ip="${octeto[0]}.${octeto[1]}.${octeto[2]}.$i"
        echo "Haciendo ping a $ip..."
        ping -c 1 -w 1 $ip > /dev/null && echo -e "\e[32m$ip está activo\e[0m" && echo $ip >> $ipsa
        done
elif [ $mascara = '16' ]
then
        for i in {1..254}
        do
                for j in {1..254}
                do
                ip="${octeto[0]}.${octeto[1]}.$i.$j"
                echo "Haciendo ping a $ip..."
                ping -c 1 -w 1 $ip > /dev/null && echo -e "\e[32m$ip está activo\e[0m" && echo $ip >> $ipsa
                done
        done
elif [ $mascara = '8' ]
then
        for i in {1..254}
        do
                for j in {1..254}
                do
                        for k in {1..254}
                        do
                        ip="${octeto[0]}.$i.$j.$k"
                        echo "Haciendo ping a $ip..."
                        ping -c 1 -w 1 $ip > /dev/null && echo -e "\e[32m$ip está activo\e[0m" && echo $ip >> $ipsa
                        done
                done
        done
fi
#Vamos a pedir al usuario los puertos para verificar si están abiertos en las IPs que están activas
echo -e "\e[34mIntroduce los puertos que quieres escanear separados por espacios (p.e. 22 80 443...)\e[0m"
read puertos
#Para saber que servicio tiene cada puerto, vamos a usar el archivo tcp.csv
tcp_csv="tcp.csv"
#Ahora vemos a leer cada linea del archivo ips_activas para ver si los puertos
#que el usuario nos pasó están activos en esas IPs
while IFS= read -r ip
do
#ahora vamos a escanear los puertos que nos dio el usuario
        for puerto in $puertos
        do
                result=$( nc -zv -w 1 $ip $puerto 2>&1 )
                servicio=$( grep ",$puerto," "$tcp_csv" | cut -d ',' -f 3 | tr -d '"' )
                if echo $result | grep -q 'succeeded'
                then
                respuesta=$( echo -e "\e[32m$ip puerto $puerto ($servicio) abierto.\e[0m")
                echo $respuesta >> $puertos_abiertos
                echo $respuesta
                fi
        done
done < $ipsa
#Para la deteccion de sistemas operativos
sistema="sistema_operativo.txt"
> $sistema
while IFS= read -r ip
do
        resultado_ttl=$(ping -c 1 -w 1 $ip | grep ttl )
        if echo $resultado_ttl | grep -q 'ttl=64'
        then
                rsistema=$(echo -e "\e[33m$ip: Tiene Sistema Operativo Linux. \e[0m")
                echo $rsistema
        elif echo $resultado_ttl | grep -q 'ttl=128'
        then
                rsistema=$( echo -e "\e[33m$ip: Tiene Sistema Operativo Windows. \e[0m" )
                echo $rsistema
        else
                rsistema=$( echo -e "\e[33m$ip Sistema Operativo desconocido. \e[0m " )
                echo $rsistema
        fi
        echo $rsistema >> $sistema
done < $ipsa


#Para guardar todos los datos en un unico archivo de salida:
echo -e "\e[34mEscribe el nombre del archivo de salida donde se guardarán todos los datos: \e[0m"
read file
archivo_salida="$file.txt"
> $archivo_salida
echo -e "\e[32m--- Resultados del Escaneo ---\e[0m" >> $archivo_salida     
echo -e "Escaneo realizado:\e[34m $(date)\e[0m" >> $archivo_salida
echo "" >> $archivo_salida

#IPs activas
echo "IPs activas:" >> $archivo_salida
cat $ipsa >> $archivo_salida  #con esto se guarda el contenido de ips_activas.txt
echo "" >> $archivo_salida

#Puertos abiertos
echo "Puertos abiertos: " >> $archivo_salida
cat $puertos_abiertos >> $archivo_salida  #con esto se guarda el contenido de puertos_abiertos.txt
echo "" >> $archivo_salida

# Sistemas operativos detectados
echo "Sistemas operativos detectados:" >> $archivo_salida
cat $sistema >> $archivo_salida  #con esto se guarda el contenido de sistema_operativo.txt
echo "" >> $archivo_salida

# Mensaje final por pantalla y en el archivo
echo -e "\e[31mEscaneo completado.\e[0m"
echo -e "\e[31mTodos los resultados han sido guardados en $archivo_salida.\e[0m"