# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "servidor2"
  end
  config.vm.network "public_network", ip: "10.0.0.2"
end
